### ISSUE TITLE
Tracking Issue on ALOHA Performance improvement using dora-rs

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora-lerobot#1]
## Performance 

- [x] Rust rewrite of teleop for lower than 20ms latency
    - [`one_side_teleop.py`](https://github.com/tonyzhaozh/aloha/blob/fbe8692b49167b5675ef3fd4031b94f015aafa20/aloha_scripts/one_side_teleop.py) seems to not be super efficient, and has a DT=20ms. [It seems that 20ms is noticeable](https://forums.steinberg.net/t/solved-latency-around-10-20ms-is-it-noticable/850675/11) so maybe try to aim for like 10ms?
    - Rust can deliver on multithreaded-concurrent subscribing and publishing

- [x] Faster Webcam latency, enable real-time visualization? Faster End-to-End Inference?
  - [`sudo apt-get install ros-noetic-usb-cam && sudo apt-get install ros-noetic-cv-bridge`](https://github.com/tonyzhaozh/aloha/blob/fbe8692b49167b5675ef3fd4031b94f015aafa20/aloha_scripts/robot_utils.py#L14) This depency should be less efficient than using cv2 from dora-rs IMO but need to try it out. Also could be hard to install on certain computers.

## Tooling

- [x] Move matplotlib to rerun.io
    - [`visualize_episodes.py`](https://github.com/tonyzhaozh/aloha/blob/main/aloha_scripts/visualize_episodes.py) this script can probably also be optimized using a dora-rerun node, using also multithreaded concurrent visualization.

- [ ] Multithreaded concurrent recording 
    - [`record_episodes.py`](https://github.com/tonyzhaozh/aloha/blob/main/aloha_scripts/record_episodes.py) this script should be optimisable using dora-record, albeit tweak dora-record to record ROS/ROS2 messages

## Ergonomy

- [x] Enable more than Python 3.8 and Ubuntu 20.04
    - [`conda create -n aloha python=3.8.10`](https://github.com/tonyzhaozh/aloha/tree/main?tab=readme-ov-file#software-installation---conda) Also this is is not major, I feel like this could be a very big frustrating point
    - [Ubuntu 20.04](https://github.com/tonyzhaozh/aloha/tree/main?tab=readme-ov-file#software-selection----os) This could be a big pain point as not everyone can switch OS easily. So fixing this can enable mass-audience.

## Hardware

- [ ] Use Gripper with GoPRO as proxy for teleoperation of smaller arms.

**Comment by Hennzau** [comment]
Regarding your "Ergonomy points," it would be great to create a Docker image with everything needed to run dora-lerobot on Aloha Arms:

- Ensure compatibility with multiple operating systems.
- Enable the creation of images for multiple architectures.
- Ensure that the Python environment is correctly installed.

I can try to make it, tell me if it's good or if it's too early

**Comment by haixuanTao** [comment]
I mean, i think dora-lerobot should be natively cross-platform and multi-architecture and it already is I think.

A good conda, pip or poetry environment description could really help but I don't think that we should spend to much time on docker images as well as maybe a quick cargo install description.

I know that docker image can be easily failure prone and hard to maintain.

Also, peolpe might already use docker and we don't to do docker in docker

**Comment by Hennzau** [comment]
I see! I'll probably do something about env description
